#!/bin/bash
echo "TEST=spec"
cd $POOL_DIR/run/
time -p $POOL_DIR/run/app_* 2.1.dict -batch
ret=$?
cd $TEST_DIR
MDHASH=`md5sum $POOL_DIR/run/test.out | awk '{ print $1 }'`
echo "HASH=$MDHASH"
rm $POOL_DIR/run/test.out
exit $ret
