#!/bin/bash
echo "TEST=spec"
cd $POOL_DIR/run/
time -p $POOL_DIR/run/app_* train
ret=$?
cd $TEST_DIR
MDHASH=`md5sum $POOL_DIR/run/train.pin | awk '{ print $1 }'`
echo "HASH=$MDHASH"
rm $POOL_DIR/run/train*
exit $ret

