#!/bin/bash
echo "TEST=spec"
cd $POOL_DIR/run/
time -p $POOL_DIR/run/app_* chair.control.cook chair.camera chair.surfaces chair.cook.ppm ppm pixels_out.cook
ret=$?
cd $TEST_DIR
MDHASH=`md5sum $POOL_DIR/run/pixels_out.cook | awk '{ print $1 }'`
echo "HASH=$MDHASH"
rm $POOL_DIR/run/pixels_out.cook
exit $ret
