#!/bin/sh

# target-run-single-test > single-test-results
# POOL_DIR - path to pool

# This script should run the test using the executables from $POOL_DIR/run

echo "This is new run"

# It's very simple application, so print here one common hash value for each test run.
#echo "HASH=123"

HASH=`md5sum $POOL_DIR/run/new | awk '{print $1}'`
cat $POOL_DIR/run/new
EXIT_CODE=$?
echo "HASH=deadbeef"
exit $EXIT_CODE

